### ISSUE TITLE
Other index error in lattice parser

### ISSUE THREAD

**Issue by anakin87** [camelot-dev/camelot#104]
I tried to extract tables from this [PDF](https://github.com/camelot-dev/camelot/files/3950873/191204A61SO2.pdf) with the following code:
`tables=camelot.read_pdf('mydoc.pdf', flavor='lattice' , line_scale=80, pages='1-end')`

**Error**
Traceback (most recent call last):

  File "/usr/src/app/swagger_server/services/extract_tables_from_pdf.py", line 108, in extract_tables_from_path
    tables = camelot.read_pdf(filename, pages=pages_string, **params_set)
  File "/usr/local/lib/python3.6/site-packages/camelot/io.py", line 106, in read_pdf
    layout_kwargs=layout_kwargs, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/camelot/handlers.py", line 162, in parse
    layout_kwargs=layout_kwargs)
  File "/usr/local/lib/python3.6/site-packages/camelot/parsers/lattice.py", line 359, in extract_tables
    table = self._generate_table(table_idx, cols, rows, v_s=v_s, h_s=h_s)
  File "/usr/local/lib/python3.6/site-packages/camelot/parsers/lattice.py", line 293, in _generate_table
    table = table.set_border()
  File "/usr/local/lib/python3.6/site-packages/camelot/core.py", line 484, in set_border
    self.cells[r][0].left = True
IndexError: list index out of range

**Comment by JSB97** [comment]
Have there been any developments on this issue?
I get a similar issue when reading [this document](http://ke.kabupro.jp/tsp/20190520/140120190516429273.pdf)

```
>>> tables = camelot.read_pdf('140120190516429273.pdf',flavor='lattice' , pages='all',suppress_stdout=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mm/.pyenv/versions/3.8.1/lib/python3.8/site-packages/camelot/io.py", line 113, in read_pdf
    tables = p.parse(
  File "/Users/mm/.pyenv/versions/3.8.1/lib/python3.8/site-packages/camelot/handlers.py", line 171, in parse
    t = parser.extract_tables(
  File "/Users/mm/.pyenv/versions/3.8.1/lib/python3.8/site-packages/camelot/parsers/lattice.py", line 411, in extract_tables
    table = self._generate_table(table_idx, cols, rows, v_s=v_s, h_s=h_s)
  File "/Users/mm/.pyenv/versions/3.8.1/lib/python3.8/site-packages/camelot/parsers/lattice.py", line 334, in _generate_table
    table = table.set_border()
  File "/Users/mm/.pyenv/versions/3.8.1/lib/python3.8/site-packages/camelot/core.py", line 535, in set_border
    self.cells[0][c].top = True
IndexError: list index out of range
```

```
>>> tables = camelot.read_pdf('140120190516429273.pdf',flavor='lattice' , line_scale=80, pages='all',suppress_stdout=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mm/.pyenv/versions/3.8.1/lib/python3.8/site-packages/camelot/io.py", line 113, in read_pdf
    tables = p.parse(
  File "/Users/mm/.pyenv/versions/3.8.1/lib/python3.8/site-packages/camelot/handlers.py", line 171, in parse
    t = parser.extract_tables(
  File "/Users/mm/.pyenv/versions/3.8.1/lib/python3.8/site-packages/camelot/parsers/lattice.py", line 411, in extract_tables
    table = self._generate_table(table_idx, cols, rows, v_s=v_s, h_s=h_s)
  File "/Users/mm/.pyenv/versions/3.8.1/lib/python3.8/site-packages/camelot/parsers/lattice.py", line 332, in _generate_table
    table = table.set_edges(v_s, h_s, joint_tol=self.joint_tol)
  File "/Users/mm/.pyenv/versions/3.8.1/lib/python3.8/site-packages/camelot/core.py", line 509, in set_edges
    self.cells[L][J].bottom = True
IndexError: list index out of range
```

**Comment by Planlos5000** [comment]
Has there been any development on this issue?
I get the following traceback

```
File "/app/pdf_extractor/extractors/table_extractor.py", line 43, in _camelot_extract
    tables = camelot.read_pdf(
  File "/usr/local/lib/python3.11/site-packages/camelot/io.py", line 113, in read_pdf
    tables = p.parse(
  File "/usr/local/lib/python3.11/site-packages/camelot/handlers.py", line 176, in parse
    t = parser.extract_tables(
  File "/usr/local/lib/python3.11/site-packages/camelot/parsers/lattice.py", line 431, in extract_tables
    table = self._generate_table(table_idx, cols, rows, v_s=v_s, h_s=h_s)
  File "/usr/local/lib/python3.11/site-packages/camelot/parsers/lattice.py", line 351, in _generate_table
    table = table.set_edges(v_s, h_s, joint_tol=self.joint_tol)
  File "/usr/local/lib/python3.11/site-packages/camelot/core.py", line 506, in set_edges
    self.cells[L][J].bottom = True
IndexError: list index out of range
```

I found, that `self.rows` (line 497) is an empty list wich results in `L = -1`.
