### ISSUE TITLE
camelot module missing after import on macbook pro 10.13.6

### ISSUE THREAD

**Issue by fdebenedetti** [camelot-dev/camelot#149]
>>> import camelot
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/apple/miniconda3/lib/python3.7/site-packages/camelot/__init__.py", line 6, in <module>
    from .io import read_pdf
  File "/Users/apple/miniconda3/lib/python3.7/site-packages/camelot/io.py", line 5, in <module>
    from .handlers import PDFHandler
  File "/Users/apple/miniconda3/lib/python3.7/site-packages/camelot/handlers.py", line 9, in <module>
    from .parsers import Stream, Lattice
  File "/Users/apple/miniconda3/lib/python3.7/site-packages/camelot/parsers/__init__.py", line 4, in <module>
    from .lattice import Lattice
  File "/Users/apple/miniconda3/lib/python3.7/site-packages/camelot/parsers/lattice.py", line 26, in <module>
    from ..image_processing import (
  File "/Users/apple/miniconda3/lib/python3.7/site-packages/camelot/image_processing.py", line 3, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
>>> import platform; print(platform.platform())
Darwin-17.7.0-x86_64-i386-64bit
>>> import sys; print('Python', sys.version)
Python 3.7.6 (default, Jan  8 2020, 13:42:34) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
>>> import numpy; print('NumPy', numpy.__version__)
NumPy 1.18.4
>>> import cv2; print('OpenCV', cv2.__version__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'cv2'
>>> import camelot; print('Camelot', camelot.__version__)

**Comment by fdebenedetti** [comment]
The one parameter I see that I am wondering about is the Darwin OS because I see in Anaconda.sh, it checks for configuration, and wont install if its equal to 'Darwin' configuration but the miniconda did not have that check.  Does it have same limitation?

**Comment by fdebenedetti** [comment]
my need is to import text from pdf into MySQL.

**Comment by everetr** [comment]
I'm also getting a "No module 'cv2'" error, but with `camelot-python` 0.8.2 on Ubuntu 18.04. This fixed it for me:

```sh
poetry add opencv-python
```

Most people probably use `pip`, so `pip install opencv-python` might do it.

For some reason, `opencv-python` is in `camelot`'s `requirements.txt` but isn't installed by `poetry`/`pip`.

**Comment by vinayak-mehta** [comment]
The default installation instructions for `pip` should work, like @everetr mentioned.
