### ISSUE TITLE
IndexError: list index out of range when specifying the area of table

### ISSUE THREAD

**Issue by Colanim** [camelot-dev/camelot#200]
## File

[202.pdf](https://github.com/camelot-dev/camelot/files/5406925/202.pdf)

## Description

When specifying `table_areas`, I'm having the following error :

>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/remondn/.venv/prospector/lib/python3.6/site-packages/camelot/io.py", line 117, in read_pdf
    **kwargs
  File "/home/remondn/.venv/prospector/lib/python3.6/site-packages/camelot/handlers.py", line 172, in parse
    p, suppress_stdout=suppress_stdout, layout_kwargs=layout_kwargs
  File "/home/remondn/.venv/prospector/lib/python3.6/site-packages/camelot/parsers/lattice.py", line 411, in extract_tables
    table = self._generate_table(table_idx, cols, rows, v_s=v_s, h_s=h_s)
  File "/home/remondn/.venv/prospector/lib/python3.6/site-packages/camelot/parsers/lattice.py", line 332, in _generate_table
    table = table.set_edges(v_s, h_s, joint_tol=self.joint_tol)
  File "/home/remondn/.venv/prospector/lib/python3.6/site-packages/camelot/core.py", line 509, in set_edges
    self.cells[L][J].bottom = True
IndexError: list index out of range

## Code to reproduce

With the given file :

```python
import camelot
camelot.read_pdf('202.pdf')
```

work as expected. But if I try to specify the table areas :

```python
import camelot
camelot.read_pdf('202.pdf', table_areas=['207,304,339,293'])
```

then I have the error.

## Expected behavior

As you can see from the PDF, this is not an actual table. I don't expect any meaningful content from this, **but I do expect no error**.

**Or should I assume if an exception is raised then it's not a table ?**

If it's the case, how to handle cases with several tables in one page and one fail ?

**Comment by vinayak-mehta** [comment]
> As you can see from the PDF, this is not an actual table. I don't expect any meaningful content from this, but I do expect no error.

That makes sense, I'll check out why it's raising an error in this case, I think it's because of this diagrams.

> Or should I assume if an exception is raised then it's not a table ?

There can be other cases where you might get a `<TableList n=0>` when no tables are found. 

> If it's the case, how to handle cases with several tables in one page and one fail ?

Can tables and diagrams both occur on the same page?

**Comment by Colanim** [comment]
Thanks for the answer @vinayak-mehta 

> Can tables and diagrams both occur on the same page?

Yes unfortunately T.T

**Comment by skytwosea** [comment]
I have the exact same problem: defining a region with table_regions causes otherwise functional code to return an IndexError. There are no diagrams in my pdf, only a table from which I need to extract only a part.

Has there been any progress on this issue?
