### ISSUE TITLE
TypeError: 'NumberObject' object is not subscriptable

### ISSUE THREAD

**Issue by hubutui** [camelot-dev/camelot#239]
**Describe the bug**
TypeError: 'NumberObject' object is not subscriptable

**Steps to reproduce the bug**
Steps used to install `camelot`:
1. `conda create --name camelot -c conda-forge camelog-py -y`

1. Add step here (you can add more steps too)

**Expected behavior**

**Code**
Add the Camelot code snippet that you used.
```bash
camelot --output result.csv --format csv lattice output.pdf
# add your code here
```

**PDF**
Add the PDF file that you want to extract tables from.

**Screenshots**

**Environment**
 - OS: ArchLinux
 - Python version: 3.9.2
 - Numpy version: 1.20.2
 - OpenCV version: 4.5.2
 - Ghostscript version: 9.53.3
 - Camelot version: 0.8.2

**Additional context**
error log:
```text
Traceback (most recent call last):
  File "/home/hubutui/.conda/envs/camelot/bin/camelot", line 10, in <module>
    sys.exit(cli())
  File "/home/hubutui/.conda/envs/camelot/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/hubutui/.conda/envs/camelot/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/hubutui/.conda/envs/camelot/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/hubutui/.conda/envs/camelot/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/hubutui/.conda/envs/camelot/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/hubutui/.conda/envs/camelot/lib/python3.9/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/hubutui/.conda/envs/camelot/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/hubutui/.conda/envs/camelot/lib/python3.9/site-packages/camelot/cli.py", line 204, in lattice
    tables = read_pdf(
  File "/home/hubutui/.conda/envs/camelot/lib/python3.9/site-packages/camelot/io.py", line 113, in read_pdf
    tables = p.parse(
  File "/home/hubutui/.conda/envs/camelot/lib/python3.9/site-packages/camelot/handlers.py", line 165, in parse
    self._save_page(self.filepath, p, tempdir)
  File "/home/hubutui/.conda/envs/camelot/lib/python3.9/site-packages/camelot/handlers.py", line 106, in _save_page
    infile = PdfFileReader(fileobj, strict=False)
  File "/home/hubutui/.conda/envs/camelot/lib/python3.9/site-packages/PyPDF2/pdf.py", line 1084, in __init__
    self.read(stream)
  File "/home/hubutui/.conda/envs/camelot/lib/python3.9/site-packages/PyPDF2/pdf.py", line 1805, in read
    assert xrefstream["/Type"] == "/XRef"
TypeError: 'NumberObject' object is not subscriptable

```

**Comment by hubutui** [comment]
I try to remove watermark from the pdf file by edit the pdf file with vim, and delete a `BBox`, and then this happens.
I also try to delete the object contains the `BBox` completely (contents from line `55 0 obj` to line `endobj`), and this still happen.
So, I think I shoud not edit the pdf file by vim. And things works as expected.

**Comment by phoewass** [comment]
You are correct, you should not edit pdfs with vim there are better ways (more reliable).
