### ISSUE TITLE
try to read "Rechnungsdetails" from an Amazon invoice from Germany

### ISSUE THREAD

**Issue by InLaw** [camelot-dev/camelot#304]
**Describe the bug**

**Steps to reproduce the bug**
try to read "Rechnungsdetails" from an Amazon invoice from Germany

**Expected behavior**
would be nice if table structure could get read

**Code**
```
import camelot
# import camelot.io as camelot

tables = camelot.read_pdf( "/home/user/AmazonGermanyInvoice.pdf"  )
tables._tables
Out[27]: []

```

**PDF**

**Screenshots**
![202205-22_1842_43__](https://user-images.githubusercontent.com/16096709/169706243-b0dfc560-370d-452b-8bef-6b19a3e8d886.png)

**Environment**

- OS: Linux 5.15.39
- Python version: Python 3.9.12
- Numpy version: 1.21.2
- OpenCV version: 4.5.4
- Ghostscript version: 9.53.3
- Camelot version: 0.10.1

**Additional context**

**Comment by bosd** [comment]
Have you tried parsing it using excalibur?
Maybe you first need to define the stream settings.

**Comment by InLaw** [comment]
Working with Nixos

`excalibur initdb`
```
Traceback (most recent call last):
  File "/nix/store/xh5lm65ww7q0ljw9x52b7zijhcigpgyy-python3.9-excalibur-py-0.4.3/bin/.excalibur-wrapped", line 6, in <module>
    from excalibur.cli import cli
  File "/nix/store/jglrmpri41n3gv2k2xpjb79jx0n5d2ph-buildEnv__pdf2csv_gs/lib/python3.9/site-packages/excalibur/cli.py", line 10, in <module>
    from .tasks import split, extract
  File "/nix/store/jglrmpri41n3gv2k2xpjb79jx0n5d2ph-buildEnv__pdf2csv_gs/lib/python3.9/site-packages/excalibur/tasks.py", line 13, in <module>
    from camelot.ext.ghostscript import Ghostscript
ModuleNotFoundError: No module named 'camelot.ext'
```

**Comment by saidakyuz** [comment]
camelots default parsing method is the lattice. Lattice is used for tables with detectable borders. The second method is the stream and distinguishes cells using the margin(gap) between text. Try to use;
```
camelot.read_pdf("ypur_path.pdf", flavor = stream)
```
