### ISSUE TITLE
Please make sure that Ghostscript is installed on macOS M1

### ISSUE THREAD

**Issue by tekumara** [camelot-dev/camelot#332]
```
Python 3.9.13 (main, Jun 11 2022, 10:29:44)
[Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import camelot
>>> camelot.__version__
'0.9.0'
>>> tables = camelot.read_pdf("Transactions.pdf")
Traceback (most recent call last):
  File "/Users/tekumara/.virtualenvs/tmp-860c6f16f3893c/lib/python3.9/site-packages/camelot/ext/ghostscript/_gsprint.py", line 260, in <module>
    libgs = cdll.LoadLibrary("libgs.so")
  File "/Users/tekumara/.pyenv/versions/3.9.13/lib/python3.9/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/Users/tekumara/.pyenv/versions/3.9.13/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(libgs.so, 0x0006): tried: 'libgs.so' (no such file), '/usr/local/lib/libgs.so' (no such file), '/usr/lib/libgs.so' (no such file), '/Users/tekumara/.virtualenvs/tmp-860c6f16f3893c/libgs.so' (no such file)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tekumara/.virtualenvs/tmp-860c6f16f3893c/lib/python3.9/site-packages/camelot/io.py", line 113, in read_pdf
    tables = p.parse(
  File "/Users/tekumara/.virtualenvs/tmp-860c6f16f3893c/lib/python3.9/site-packages/camelot/handlers.py", line 173, in parse
    t = parser.extract_tables(
  File "/Users/tekumara/.virtualenvs/tmp-860c6f16f3893c/lib/python3.9/site-packages/camelot/parsers/lattice.py", line 402, in extract_tables
    self._generate_image()
  File "/Users/tekumara/.virtualenvs/tmp-860c6f16f3893c/lib/python3.9/site-packages/camelot/parsers/lattice.py", line 211, in _generate_image
    from ..ext.ghostscript import Ghostscript
  File "/Users/tekumara/.virtualenvs/tmp-860c6f16f3893c/lib/python3.9/site-packages/camelot/ext/ghostscript/__init__.py", line 24, in <module>
    from . import _gsprint as gs
  File "/Users/tekumara/.virtualenvs/tmp-860c6f16f3893c/lib/python3.9/site-packages/camelot/ext/ghostscript/_gsprint.py", line 267, in <module>
    raise RuntimeError("Please make sure that Ghostscript is installed")
RuntimeError: Please make sure that Ghostscript is installed
```

Ghostscript has been installed via `brew install ghostscript`

**Comment by tekumara** [comment]
To resolve set
```
export DYLD_LIBRARY_PATH=/opt/homebrew/Cellar/ghostscript/10.0.0/lib/
```
