### ISSUE TITLE
Issue in handlers.py 

### ISSUE THREAD

**Issue by code4efa4code** [camelot-dev/camelot#365]
>>> tables=camelot.read_pdf('C:/Users/e/Manual.pdf',pages=164) 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\e\.venv\lib\site-packages\camelot\io.py", line 111, in read_pdf
    p = PDFHandler(filepath, pages=pages, password=password)
  File "C:\Users\e\.venv\lib\site-packages\camelot\handlers.py", line 50, in __init__
    self.pages = self._get_pages(pages)
  File "C:\Users\e\.venv\lib\site-packages\camelot\handlers.py", line 83, in _get_pages
    for r in pages.split(","):
AttributeError: 'int' object has no attribute 'split'

This resolved it for me 
for r in  str(pages).split(","):

**Comment by lipsa7** [comment]
Hi @code4efa4code, can you please help me with an error?

I ran the code tables.export('foo.xlsx', f='excel'), but it is throwing me an error:
TypeError: NDFrame.to_excel() got an unexpected keyword argument 'encoding'

Can you please help with this?

**Comment by DoomedJupiter** [comment]
This was likely due to passing the `pages` argument as an integer and not as a string (`pages=1` vs `pages='1'`). I made the same mistake when I first used the package. The correct syntax is not easily found in the documentation, recommend improving the documentation to make this clear for new users. It might also be worthwhile to check the type and throw an error and alerting the user that the argument should be a string.

**Comment by bosd** [comment]
Closing — the traceback predates the v2 backend rewrite.

The stack trace points into `camelot/handlers.py` lines 50 + 83 (the old `_get_pages` body before the playa migration). v2 replaced that whole code path with a lazy property + `playa.open()`-based page resolution, so the specific traceback you posted can no longer reproduce.

If you still hit a parse failure on page 164 of your Manual.pdf on `>=1.0.x`, please open a fresh issue with:
- the camelot version
- the new (post-v2) traceback
- a minimal repro

so we can dig in against the current code.
