### ISSUE TITLE
estract only and always first page by this type pdf generate by Oracle

### ISSUE THREAD

**Issue by elyparker** [camelot-dev/camelot#378]
**Describe the bug**
I have to extract tables from pdf file generated from **Oracle Reports 10gR2**

for first page only ok  but aftr second page and other i cannot access completely

example of file
[oda_2.pdf](https://github.com/camelot-dev/camelot/files/11536448/oda_2.pdf)

**Steps to reproduce the bug**
in a  folder where is file oda_2.pdf

i launch python shell

```
import camelot
handler = camelot.handlers.PDFHandler("oda_2.pdf",'all')
 page_list = handler._get_pages("oda_2.pdf")
```
_Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\camelot\handlers.py", line 90, in _get_pages
    page_numbers.append({"start": int(r), "end": int(r)})
ValueError: invalid literal for int() with base 10: 'oda_2.pdf'_

```
 tables=camelot.read_pdf("oda_2.pdf", flavor='stream', page=**2**)
 print (tables[0].parsing_report)
```
{'accuracy': 93.8, 'whitespace': 70.16, 'order': 1, 'page': 1}
` print (tables[0].df)`

output = table of first page not second

camelot, version 0.11.0
Python 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] on win32

i think that pdf  files is malformed but acroread and other program open it, why camelot not?

do it exist a way?
thank

**Comment by bosd** [comment]
Closing.

Without a fresh reproduction on current master, I can't tell whether this still bites against the v2 backend (the playa migration changed the page-iteration code substantially — the previous backend opened the PDF once per page via a temp-file-split that occasionally silently dropped pages on certain PDF generators, Oracle Reports' included).

If you can still reproduce on a recent install (`pip install -U camelot-py`) with `oda_2.pdf` and a recent `camelot.read_pdf(..., pages="all")`, please open a fresh issue with the new output. The previous behaviour was almost certainly an artefact of the per-page splitting code that's now gone.
