### ISSUE TITLE
Error: openpyxl.utils.exceptions.IllegalCharacterError

### ISSUE THREAD

**Issue by olivierberten** [camelot-dev/camelot#42]
```
ERROR:root:
Traceback (most recent call last):
  File "/home/myusername/.local/lib/python3.7/site-packages/excalibur/tasks.py", line 123, in extract
    tables.export(f_datapath, f=f, compress=True)
  File "/home/myusername/.local/lib/python3.7/site-packages/camelot/core.py", line 745, in export
    table.df.to_excel(writer, sheet_name=sheet_name, encoding="utf-8")
  File "/home/myusername/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 2257, in to_excel
    engine=engine,
  File "/home/myusername/.local/lib/python3.7/site-packages/pandas/io/formats/excel.py", line 739, in write
    freeze_panes=freeze_panes,
  File "/home/myusername/.local/lib/python3.7/site-packages/pandas/io/excel/_openpyxl.py", line 416, in write_cells
    xcell.value, fmt = self._value_with_fmt(cell.val)
  File "/home/myusername/.local/lib/python3.7/site-packages/openpyxl/cell/cell.py", line 252, in value
    self._bind_value(value)
  File "/home/myusername/.local/lib/python3.7/site-packages/openpyxl/cell/cell.py", line 205, in _bind_value
    value = self.check_string(value)
  File "/home/myusername/.local/lib/python3.7/site-packages/openpyxl/cell/cell.py", line 169, in check_string
    raise IllegalCharacterError
openpyxl.utils.exceptions.IllegalCharacterError
```

By the way, which is the official issue tracker? This one or https://github.com/atlanhq/camelot/issues

**Comment by vinayak-mehta** [comment]
@olivierberten Can you also post the PDF that raised this error? This is the official issue tracker.
